package:
  name: seaborn
  version: 0.13.2
  top-level:
    - seaborn
source:
  url: https://files.pythonhosted.org/packages/py3/s/seaborn/seaborn-0.13.2-py3-none-any.whl
  sha256: 636f8336facf092165e27924f223d3c62ca560b1f2bb5dff7ab7fad265361987
requirements:
  run:
    - numpy
    - pandas
    - matplotlib
about:
  home: https://seaborn.pydata.org
  PyPI: https://pypi.org/project/seaborn
  summary: Statistical data visualization
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - rpwagner